config/routes.rb
FitBitch::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
	get "users/fitbit" => "users#fitbit"
  post "users/fitbit_connect" => "users#fitbit_connect"

  get "users/twitter" => "users#twitter"
	post "users/twitter_connect" => "users#twitter_connect"

  root :to => "home#index"
  match "/home/check_status" => "home#check_status"

  resources :messages
  match "/messages/send_sms" => "messages#send_sms"
  match "/messages/send_email" => "messages#send_email"
  match "/messages/send_email_all" => "messages#send_email_all"
  match "/messages/send_email_pete" => "messages#send_email_pete"

  resources :texts, :emails, :tweets
end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :user
  belongs_to :content
  belongs_to :meme

  attr_accessible :user_id, :content_id, :meme_id

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  @multiple = false

  def index
  end

  def new
    @users = User.all
  end

  def send_sms
    user = User.find(params[:user])

    rand_content_id = rand(Content.count)+1

    Text.new.send_message(user, Content.find(rand_content_id))

    redirect_to new_message_path
  end

  def send_email(user=nil, subject=nil, rand_meme_id=nil)
    user = User.find(params[:user]) unless user
    logger.info(user)
    puts user.inspect
    puts user.email
    puts user.current_steps

    if subject.to_s["FIRST_NAME"]
      subject["FIRST_NAME"] = user.email
    end

    rand_meme_id = rand(Meme.count)+1 unless rand_meme_id

    Email.new.send_message(user, Meme.find(rand_meme_id), subject)

    if !@multiple
      redirect_to new_message_path
    end
  end

  def send_email_all
    @multiple = true

    rand_meme_id = rand(Meme.count)+1

    User.all.each { |user| 
      send_email(user, "Fitness levels ain't looking so good for FIRST_NAME", rand_meme_id)
    }

    redirect_to new_message_path
  end

  def send_email_pete
    send_email(
      User.where(:email => 'pt9386@gmail.com')[0],
      nil,
      Meme.where(:image_url => 'http://cdn.memegenerator.net/instances/400x/26423750.jpg')[0]
    )
  end
end

app/views/messages/index.html.erb
<h1>Messages</h1>

<div><%= link_to "Create New Message", new_message_path %></div>

app/views/messages/new.html.erb
<h1>Send Message</h1>

<%= form_tag messages_send_email_pete_path do %>
    <%= submit_tag "Email Pete" %>
<% end %>

<%= form_tag messages_send_email_all_path do %>
    <%= submit_tag "Email All" %>
<% end %>

<%= form_tag messages_send_email_path do %>
    <%= select_tag "user", options_from_collection_for_select(@users, "id", "email") %>
    <%= submit_tag "Email" %>
<% end %>

<%= form_tag messages_send_sms_path do %>
    <%= select_tag "user", options_from_collection_for_select(@users, "id", "email") %>
    <%= submit_tag "SMS" %>
<% end %>